name: Update Repo List

on:
  schedule:
    # 每天每 3 小时执行一次
    - cron: '0 */3 * * *'
  workflow_dispatch:
    # 允许手动触发:

jobs:
  update-repo-list:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 确保存在执行脚本
        run: chmod +x fetch_source.sh

      - name: 执行脚本
        # sleep 0.1 s，避免 github api 限制导致的请求失败
        run: ./fetch_source.sh github_api_sleep=0.1

      - name: 提交并推送变更
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repo_list.txt

          # 只检查 repo_list.txt 是否有变更（已暂存）
          if git diff --cached --quiet repo_list.txt; then
            echo "没有变更 repo_list.txt，跳过推送"
          else
            echo "repo_list.txt 修改内容:"
            git diff --cached repo_list.txt
            git commit -m "Update repo list"
            git push origin HEAD:main
            echo "提交并推送变更 repo_list.txt"
          fi
          # 检查是否有实际内容修改（排除权限变化）
          # if git diff --cached --name-only | grep -q .; then
          #   if git diff --cached --name-only | grep -v "fetch_source.sh" | grep -q .; then
          #     echo "修改内容:"
          #     git diff --cached
          #     git commit -m "Update repo list"
          #     git push origin HEAD:main
          #     echo "提交并推送变更repo_list.txt"
          #   else
          #     echo "只有fetch_source.sh权限变化，跳过推送"
          #   fi
          # else
          #   echo "没有变更，跳过推送"
          # fi
